# Generated by Django 5.1.1 on 2024-10-02 04:36

import cats.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=64, unique=True, validators=[cats.validators.TitleValidator()], verbose_name='Название породы'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=64, validators=[cats.validators.TitleValidator()], verbose_name='Кличка'),
        ),
        migrations.AddConstraint(
            model_name='breed',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_lower_name'),
        ),
    ]
