# Generated by Django 5.1.1 on 2024-10-02 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_alter_breed_name_alter_cat_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ('name',)},
        ),
    ]
